### ISSUE TITLE
Bad Request (HTTP 400). Failed to get an access token.

### ISSUE THREAD

**Issue by whs16** [pablobarbera/Rfacebook#77]
I've been following the tutorial from http://thinktostart.com/analyzing-facebook-with-r/

and ran the code:

```R
install.packages("devtools")
library(devtools)

install_github("Rfacebook", "pablobarbera", subdir = "Rfacebook")
library(Rfacebook)

fb_oauth <- fbOAuth(app_id = "XXXXX",
                    app_secret = "XXXXX",
                    extended_permissions = TRUE)
```

with the following `sessionInfo`

```R
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.3 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rook_1.1-1      Rfacebook_0.6.4 httpuv_1.3.3    rjson_0.2.15    httr_1.2.0     
[6] curl_0.9.7     

loaded via a namespace (and not attached):
[1] R6_2.1.2    tools_3.2.3 Rcpp_0.12.5 brew_1.0-6 
```

I then put `http://localhost:1410/` in the facebook app settings before running my code.
It launches a browser that says `Authentication complete. Please close this page and return to R.`

But in my R console I keep getting

```
Authentication complete.
Error in init_oauth2.0(self$endpoint, self$app, scope = self$params$scope,  : 
  Bad Request (HTTP 400). Failed to get an access token.
```

#54 suggested changing `extended_permissions = TRUE` to `extended_permissions = FALSE`
but I still get the same problem

**Comment by frmendes** [comment]
Same issue. Both with `extended_permissions = TRUE` and `extended_permissions = FALSE`.

`sessionInfo()` output:

```r
R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin15.5.0 (64-bit)
Running under: OS X 10.11.5 (El Capitan)

locale:
[1] C

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
[1] curl_0.9.7      Rfacebook_0.6.4 httpuv_1.3.3    rjson_0.2.15   
[5] httr_1.2.0     

loaded via a namespace (and not attached):
[1] R6_2.1.2    tools_3.3.0 Rcpp_0.12.5
```

**Comment by neomedeiros** [comment]
Same issue here. extended_permissions = TRUE/FALSE does not working.

SessionInfo():

R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                           LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rfacebook_0.6.4 httpuv_1.3.3    rjson_0.2.15    devtools_1.11.1 httr_1.2.0     

loaded via a namespace (and not attached):
[1] R6_2.1.2      tools_3.3.0   withr_1.0.1   curl_0.9.7    memoise_1.0.0 Rcpp_0.12.5   git2r_0.15.0  digest_0.6.9

**Comment by KDamoah** [comment]
Same issue with me , I have been trying for 3 days now
> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rfacebook_0.6.4 httpuv_1.3.3    rjson_0.2.15    httr_1.2.0     

loaded via a namespace (and not attached):
[1] R6_2.1.2    tools_3.3.0 curl_0.9.7  Rcpp_0.12.5

**Comment by Yu-Che-Gao** [comment]
same issue with me

` > fb.oauth <- fbOAuth(
  app_id="1813275828894179",
  app_secret="88628c9ea468c47766df58a05640eec2",
  extended_permissions = TRUE)
`

then return

`Copy and paste into Site URL on Facebook App Settings: http://localhost:1410/ 
When done, press any key to continue...
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error in init_oauth2.0(self$endpoint, self$app, scope = self$params$scope,  : 
  Bad Request (HTTP 400). Failed to get an access token.`

**Comment by sterminillo** [comment]
I am getting the same problem:

Copy and paste into Site URL on Facebook App Settings: http://localhost:1410/ 
When done, press any key to continue...fb_oauth
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
Error in init_oauth2.0(self$endpoint, self$app, scope = self$params$scope,  : 
  Bad Request (HTTP 400). Failed to get an access token.

does anyone have any ideas on how to solve this please??

**Comment by Stormseer** [comment]
I'm also getting the same issue, so I decided to poke around a little and I found the [following](https://developers.facebook.com/docs/apps/changelog): 

> **All Callback Subscriptions Must Use HTTPS** - When we launched Graph API v2.5 last October we began requiring new Webhooks (formerly known as Real Time Updates) subscriptions to be configured for HTTPS. With v2.6, this is now required for all new Dynamic Pricing and Deauthorization endpoints as well. Beginning 90 days from today, we will require all callback subscriptions to be configured for HTTPS. At that point, we will stop sending updates to non-HTTPS endpoints, regardless of when they were created. This applies to Webhooks, Webhooks for Payments, Dynamic Pricing, and Deauthorization. You can update your subscriptions on your app dashboard.

I believe this issue is caused by Rfacebook using HTTP, which is no longer supported.

**Comment by lyons422** [comment]
Have the same issue and resolve the HTTP 400 by downgrade the httr to 1.1.0 from 1.2.0.

Use the following the commands to give a try.

_library(devtools)
install_version("httr", version = "1.1.0", repos = "http://cran.us.r-project.org")
library(httr)_

**Comment by pablobarbera** [comment]
This should be fixed in the new version on GitHub (soon on CRAN). I thought it was the scope settings, but actually with httr 1.2 now it's not necessary to set the httr server port manually anymore, and that seemed to be the problem.

Thanks everyone for reporting this!

**Comment by emillykkejensen** [comment]
I still get the error code "Bad Request (HTTP 400). Failed to get an access token."

Have updated to Rfacebook 0.6.7 and httr 1.2.1

**Comment by brianpenghe** [comment]
Still have the same error

**Comment by ahdvnd** [comment]
Is this issue closed? I still get the same error with the most recent versions of fbrads and httr.

**Comment by LyaSolis** [comment]
Same here - is it due to FB restrictions?

**Comment by krinya** [comment]
Does someone have a solution?

**Comment by akiraFuk** [comment]
I have the same problem.

But i try to do wothout app domain, just with site URL in facebook config and works for me.

**Comment by netododono** [comment]
I've the same problem. I'm following the steps at http://thinktostart.com/analyzing-facebook-with-r/ and when R opens a window in my browser I see an error like this: this URL isn't included in your app's domains. 
When I click in "Ok", I see "Authentication complete". Then I close and I see the same error in R.

**Comment by zhalabi** [comment]
I have the same problem here. 


R version 3.3.2 (2016-10-31)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: macOS  10.13.2

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rfacebook_0.6.15 httpuv_1.3.5     rjson_0.2.15     httr_1.3.1      

loaded via a namespace (and not attached):
[1] R6_2.2.2    tools_3.3.2 curl_3.1    Rcpp_0.12.8
>

**Comment by alexgithub56** [comment]
install.packages("Rfacebook")
install.packages("RCurl")
install.packages("devtools")
library(Rfacebook)
library(RCurl)
library(devtools)
library(tidyverse)
token <- 'xxxxxx'
me <- getUsers("me", token, private_info = TRUE)
var1 <- getPage(page = "webpage", token, since = "2018/01/01", until = "2018/03/10", n = 20000)

it's work.

**Comment by sourourarbi** [comment]
> me <- getUsers("me", token, private_info = TRUE)
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Illegal characters found in URL
it's not work for me

**Comment by voigtjessica** [comment]
> Have the same issue and resolve the HTTP 400 by downgrade the httr to 1.1.0 from 1.2.0.
> 
> Use the following the commands to give a try.
> 
> _library(devtools) install_version("httr", version = "1.1.0", repos = "http://cran.us.r-project.org") library(httr)_

I tried this, but then i get the error " Rfacebook requires httr version 1.2.0 or greater"

**Comment by alexgithub56** [comment]
Hi

Try:

install.packages("httr")

Alex
